# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
# SPDX-FileContributor: Li Guan <guanli.oerv@isrc.iscas.ac.cn>
#
# SPDX-License-Identifier: MulanPSL-2.0

%global srcname partial-json-parser
%global pypi_name partial_json_parser
%global pypi_version 0.2.1.1.post7

Name:           python-%{srcname}
Version:        0.2.1.1~post7
Release:        %autorelease
Summary:        Parse partial JSON generated by LLM
License:        MIT
URL:            https://github.com/promplate/partial-json-parser
#!RemoteAsset:  sha256:86590e1ba6bcb6739a2dfc17d2323f028cb5884f4c6ce23db376999132c9a922
Source0:        https://files.pythonhosted.org/packages/source/p/%{srcname}/%{pypi_name}-%{pypi_version}.tar.gz
BuildArch:      noarch
BuildSystem:    pyproject

BuildOption(install):  -l %{pypi_name} -L

BuildRequires:  pyproject-rpm-macros
BuildRequires:  pkgconfig(python3)
BuildRequires:  python3dist(rich)

Provides:       python3-%{srcname} = %{version}-%{release}
%python_provide python3-%{srcname}

%description
Sometimes we need LLM (Large Language Models) to produce structural
information instead of natural language. The easiest way is to use JSON.

%generate_buildrequires
%pyproject_buildrequires

%files -f %{pyproject_files}
%doc README.md
%license LICENSE
%{_bindir}/json-playground

%changelog
%autochangelog
