# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
# SPDX-FileContributor: Li Guan <guanli.oerv@isrc.iscas.ac.cn>
#
# SPDX-License-Identifier: MulanPSL-2.0

%global srcname antlr4-python3-runtime

Name:           python-%{srcname}
Version:        4.9.3
Release:        %autorelease
Summary:        ANTLR4 Python3 Runtime
License:        BSD-3-Clause
URL:            https://www.antlr.org/
VCS:            git:https://github.com/antlr/antlr4.git
#!RemoteAsset:  sha256:f224469b4168294902bb1efa80a8bf7855f24c99aef99cbefc1bcd3cce77881b
Source0:        https://files.pythonhosted.org/packages/source/a/%{srcname}/%{srcname}-%{version}.tar.gz
#!RemoteAsset:  sha256:b1b379fcaf3219593a4c433feb1b35c780bed23fafaae440b1ae2771a9521e3a
Source1:        https://raw.githubusercontent.com/antlr/antlr4/%{version}/LICENSE.txt
BuildArch:      noarch
BuildSystem:    pyproject

BuildOption(install):  -l antlr4 -L

BuildRequires:  pyproject-rpm-macros
BuildRequires:  pkgconfig(python3)

Provides:       python3-%{srcname} = %{version}-%{release}
%python_provide python3-%{srcname}

%description
The ANTLR4 Python3 Runtime is a library that provides
support for executing parsers generated by ANTLR4 in Python 3.
It includes the necessary components to run ANTLR4-generated parsers,
such as the runtime environment and utility functions.

%prep -a
cp %{SOURCE1} .

%generate_buildrequires
%pyproject_buildrequires

%files -f %{pyproject_files}
%doc README.txt
%license LICENSE.txt
%{_bindir}/pygrun

%changelog
%autochangelog
