# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
# SPDX-FileContributor: panglars <panghao.riscv@isrc.iscas.ac.cn>
#
# SPDX-License-Identifier: MulanPSL-2.0

%global srcname codecarbon

Name:           python-%{srcname}
Version:        3.2.6
Release:        %autorelease
Summary:        Estimate and track carbon emissions from computing
License:        MIT
URL:            https://codecarbon.io/
VCS:            git:https://github.com/mlco2/codecarbon.git
#!RemoteAsset:  sha256:44643ddb571fcf5de36c1a35e7fd9f0cc8bd2bb124cb97bdbd2dd6f07ea6bfc9
Source0:        https://files.pythonhosted.org/packages/source/c/%{srcname}/%{srcname}-%{version}.tar.gz
BuildArch:      noarch
BuildSystem:    pyproject

BuildOption(install):  -l %{srcname} -L
# Exclude import checks for optional modules and helper scripts
BuildOption(check):  -e codecarbon.core.measure
BuildOption(check):  -e 'codecarbon.data.*'
BuildOption(check):  -e 'codecarbon.viz.*'

BuildRequires:  pyproject-rpm-macros
BuildRequires:  pkgconfig(python3)
BuildRequires:  python3dist(arrow)
BuildRequires:  python3dist(authlib) >= 1.2.1
BuildRequires:  python3dist(click)
BuildRequires:  python3dist(nvidia-ml-py)
BuildRequires:  python3dist(pandas)
BuildRequires:  python3dist(pip)
BuildRequires:  python3dist(prometheus-client)
BuildRequires:  python3dist(psutil) >= 6
BuildRequires:  python3dist(py-cpuinfo)
BuildRequires:  python3dist(pycountry)
BuildRequires:  python3dist(pydantic)
BuildRequires:  python3dist(questionary)
BuildRequires:  python3dist(rapidfuzz)
BuildRequires:  python3dist(requests)
BuildRequires:  python3dist(rich)
BuildRequires:  python3dist(setuptools) >= 77
BuildRequires:  python3dist(typer-slim)
BuildRequires:  python3dist(wheel)

Provides:       python3-%{srcname} = %{version}-%{release}
%python_provide python3-%{srcname}

%description
CodeCarbon is a Python package that estimates and tracks the carbon emissions
generated by computing workloads. It can record CPU, GPU and RAM energy usage,
map it to regional carbon intensity data and export emissions measurements.

%prep -a
sed -i 's/"typer",/"typer-slim",/' pyproject.toml

%generate_buildrequires
%pyproject_buildrequires

%files -f %{pyproject_files}
%doc README.md
%license LICENSE
%{_bindir}/carbonboard
%{_bindir}/codecarbon

%changelog
%autochangelog
